### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/C-Sharp#1]
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by pehprado** [comment]
Hi, @AnupKumarPanwar . I can add some algorithms

**Comment by dynamitechetan** [comment]
@pehprado  Sure

**Comment by PankajLala** [comment]
Hi @AnupKumarPanwar , I can add few.

**Comment by AnupKumarPanwar** [comment]
Yeah @pankajlala go ahead

**Comment by harshildarji** [comment]
@AnupKumarPanwar It's happening. Received and merged so many PRs!
