### ISSUE TITLE
Add more data structures

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#112]
Feel free to propose and/or implement new data structures, I will add them to the list below :)
List of data structures that would be great to see in this repo:
Basic:
- [x] Sorted List

Heaps:
- [x] Fibonacci heap
- [x] Pairing heap

Trees:
- [x] Scapegoat tree
- [ ] Finger tree
- [ ] Van Emde-Boas tree
- [x] Suffix trie
- [ ] B-tree
- [ ] B+ tree
- [ ] Interval tree
- [x] Red-Black tree
- [x] AVL-tree
- [ ] Splay-tree
- [ ] Merkle tree
- [ ] R-tree
- [ ] KD-tree
- [ ] Hash array mapped trie
- [ ] Ball tree

Probabilistic:
- [ ] Quotient filter

Other:
- [ ] Rope
- [ ] Skip list
- [ ] Zipper
- [x] Disjoint set
- [ ] Work Stealing Queue
- [x] Inverted index
- [ ] Gap buffer
- [ ] Nested sets
- [ ] Half-Edge data structure
- [x] Unrolled linked list

**Comment by ivanruski** [comment]
Hi @siriak, 
I think that Binary search tree should also be in the list, because it is easier to implement than AVL and Red-black trees. However it  shares a lot of commonalities with them and this makes BST helpful when someone is starting to learn about trees to have a basic version.

**Comment by siriak** [comment]
Hi @ivanruski, sure thing! I've added Binary search tree to the list.

**Comment by DuckNrOne** [comment]
I could implement binary search tree and segment tree.

**Comment by jlechem** [comment]
Looks like the stacks are done, should update the list.

**Comment by rohansp** [comment]
@siriak I would like to contribute. any open issues ?

**Comment by siriak** [comment]
@rohansp you can take any algorithm/data structure that's not implemented yet and implement it.

**Comment by rohansp** [comment]
How to figure out which ones are implemented already?

**Comment by siriak** [comment]
You can check a list in README.md or browse directories in the repository and see in files. Also, [here](https://github.com/TheAlgorithms/C-Sharp/issues/112#issue-490317986) not implemented data structures are unchecked.

**Comment by mondalshubham1** [comment]
I want to contribute in AVL trees.

**Comment by arajaram** [comment]
Looks like AVL trees isn't done yet and I'm working on an implementation that I can contribute if it isn't done by the time I'm finished. Also going to take on Red-Black trees after I'm done with this.

**Comment by CyberMobius** [comment]
I can implement Fibonacci heaps

**Comment by siriak** [comment]
@arajaram @CyberMobius cool, go ahead!

**Comment by gedkott** [comment]
@siriak Do you think an implementation of a [dynamic array](https://en.wikipedia.org/wiki/Dynamic_array) would be worthwhile to add?

**Comment by siriak** [comment]
@gedkott IMO it'd be nice to have a dynamic array for educational purposes even though List<T> exists, which is the same thing.

**Comment by gedkott** [comment]
@siriak That makes sense. Linked lists are part of the project already, but dynamic arrays would be a good educational addition to the project given the performance and implementation differences. 

I have someone who is learning how to write a dynamic array now and I would like to have them contribute their complete solution here when ready. I'll be in touch as we progress. Let me know if there is anything we should consider as we work on it together. 

Thanks for your leadership on this project!

**Comment by phougatv** [comment]
List (Dynamic Array)

**Comment by mime8** [comment]
Hi, I'd like to implement Scapegoat tree.

**Comment by phougatv** [comment]
> 
> 
> List (Dynamic Array)

I would like to contribute. Do I need specific permission to create a branch and raise a PR?

**Comment by siriak** [comment]
@mime8 cool, go ahead!
@phougatv you don't need any permission to contribute, just make a fork, work there and make a PR once you are done :)

**Comment by kolosovpetro** [comment]
@siriak Hi, do you need a graph implementation in the Data Structures section?

**Comment by siriak** [comment]
@kolosovpetro Hi, definitely :)

**Comment by mime8** [comment]
@siriak , hi again! I'll create a PR with Scapegoat tree implementation either today or early next week. Sorry for long absence.

**Comment by Leefrost** [comment]
Hi, I would like to work with Fenwick tree

**Comment by Leefrost** [comment]
If no one takes already Inverted index, I will do it.

**Comment by mime8** [comment]
I'd like to work on B-tree next, if that's okay.

**Comment by mime8** [comment]
BTW, I think the description of this thread should be updated. Some of the data structures mentioned there are already implemented.

**Comment by siriak** [comment]
@mime8  I think I've updated it correctly, please let me know if something else was already implemented

**Comment by mime8** [comment]
@siriak , I see that SortedList and AVL tree were already implemented.

**Comment by deljohnson1** [comment]
We need a BigList. The implementation of List in C# is constrained by an integer index.

**Comment by siriak** [comment]
Let's keep track of new proposals as separate issues
