### ISSUE TITLE
I created a "BitList" that can be add to the structures

### ISSUE THREAD

**Issue by LorenzoLotti** [TheAlgorithms/C-Sharp#141]
It has more features than the BitArray structure, such as the add/remove one or more bits to an existing BitList, and is convertible to all native types and it has many more ctor.
I can send it to you to modify it as you want.

**Comment by LorenzoLotti** [comment]
Hi, i add a PR with my structure.

Il giorno lun 18 mag 2020 alle ore 19:23 Andrii Siriak <
notifications@github.com> ha scritto:

**Comment by siriak** [comment]
I'm closing this issue now as we have a PR #143 and can discuss everything related to it there. Feel free to reopen if there is a need in it.
