### ISSUE TITLE
Add search algorithms

### ISSUE THREAD

**Issue by beqakd** [TheAlgorithms/C-Sharp#145]
Lets start with jump search algorithm and add more search problems to this repository.

**Comment by beqakd** [comment]
I will assign this task to myself.

**Comment by NektariosMar** [comment]
Hey @beqakd,

Have you finished implementing the jump search algorithm or do you want help?
I'm considering to start implementing Dijkstra's algorithm

**Comment by siriak** [comment]
@NektariosMar IMO you can start working on jump searcher because #146 seems abandoned

**Comment by NektariosMar** [comment]
@siriak 
Ok cool.
I understand there were some issues with the merge. Should I start over the implementation of the jump searcher or is there a way I can pull the code that beqakd has written?

**Comment by siriak** [comment]
@NektariosMar you can fork his repo or start from scratch, it's up to you

**Comment by ikp1997** [comment]
Hi is this issue still open can I start working on it?

**Comment by siriak** [comment]
@ikp1997 yes, you can start working on that, but please take into account comments on previous PRs (#192, #185, #146)

**Comment by siriak** [comment]
I've added the jump search algorithm to #111, feel free to implement it!
