### ISSUE TITLE
Replace NUnit with xUnit testing framework

### ISSUE THREAD

**Issue by antonAce** [TheAlgorithms/C-Sharp#169]
From my perspective, NUnit has a lack of features to write unit tests with complex data on input. xUnit has attributes like **MemberData**, **ClassData** e.t.c. to make this task easier. Also, this framework provides a wider range of assertions and a more flexible way to create data generators for testing.

**Comment by siriak** [comment]
NUnit has **TestCaseSource**, which allows to do the same things as **MemberData** and **ClassData** in xUnit. As for assertions, IMO it'd be nice to make use of [Fluent Assertions](https://fluentassertions.com) because they are way better than both NUnit and xUnit.

**Comment by antonAce** [comment]
Yep, just figured out about [TestCaseSource](https://docs.nunit.org/2.5/testCaseSource.html), thanks for letting me know! Good idea about Fluent Assertions, I'll use it in the new algorithm PR :grinning:
