### ISSUE TITLE
expanding CONTRIBUTING.md

### ISSUE THREAD

**Issue by algobytewise** [TheAlgorithms/C-Sharp#210]
I just got started with contributing to this repo and it took me a while to figure out the basics of NUnit, codecov etc. I think it might be a good idea to give a short explanation in `CONTRIBUTING.md` to give new contributers in the future a head-start.

I thought something along the following lines: Please implement tests, put the test in a separate file in the algorithms-test folder, name the test-class correspondingly, we use NUnit for tests (link), a basic test can be implemented so&so, the test can be locally run so&so, we use codecov which checks that each conditional branch gets tested, please try to implement tests for the different branches of each public method.

It might also be good to add something about coding style, for example suggest a code formatter that can be locally used, but I myself don't know about that part.

If this sounds like a good idea then I would get started on a draft.

**Comment by siriak** [comment]
That's a good idea, go ahead! As for code style, it's configured in.editorconfig, stylecop.json, and stylecop.ruleset. And enforced by IDE you use (at least works in Rider and Visual Studio and there are no other modern IDEs)
