### ISSUE TITLE
Add more OEIS sequences

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#222]
Feel free to propose and/or implement new sequences, I will add them to the list below :)
List of some interesting OEIS sequences that would be great to see in this repo (but you can implement any one from OEIS, not only from this list):
- [x] A000004 Zero
- [x] A000005 Number of Divisors of n
- [x] A000008 Number of ways of making change for n cents using coins of 1, 2, 5, 10 cents
- [x] A000010 Euler totient function of n

**Comment by deljohnson1** [comment]
I'm working on:

A000009 Strict Partition sequence
A000041 Partition sequence
A000110 Bell sequence
A000111 Euler Zig Zag sequence
A000129 Pell sequence
A000166 Derangement sequence
A000217 Triangular sequence
A001003 Small Schröder sequence
A001006 Motzkin sequence
A001045 Jacobsthal sequence
A002203 Companion Pell sequence
A002378 Pronic sequence
A002487 Sterns Diatomic sequence
A002559 Markov sequence
A002858 Ulam sequence
A003261 Woodall sequence
A003601 Arithmetic sequence
A006318 Large Schröder sequence
A138591 Polite sequence
A328152 Squares on Grid sequence

**Comment by siriak** [comment]
The original list was implemented, feel free to open an issue for other sequences
