### ISSUE TITLE
Suggestion of a dynamics hierarchical layout to invite more .NET community engagement

### ISSUE THREAD

**Issue by GeorgeS2019** [TheAlgorithms/C-Sharp#276]
The GO uses **[dynamic hierarchical layout](https://github.com/TheAlgorithms/Go/blob/master/README.md)**. Perhaps C-Sharp can gradually migrate that into this layout.
Why: the community can quickly has a top overview, which algorithms have been selected and the text associated with it for community refinement and further contribution

---

## Algorithms

<details>
	<summary> <strong> Data Compression </strong> </summary>	

---

#####  Data Compression Module
>is a set of steps for packing data into a smaller space, while allowing for the original data to be seen again. Compression is a two-way process: a compression algorithm can be used to make a data package smaller, but it can also be run the other way, to decompress the package into its original form. Data compression is useful in computing to save disk space, or to reduce the bandwidth used when sending data (e.g., over the internet). : https://simple.wikipedia.org/wiki/Data_compression

---
##### Data Compression Algorithms:

<details>
<summary>Burrows-Wheeler transform</summary>

---

#####  Burrows–Wheeler transform (BWT)
>rearranges a character string into runs of similar characters. This is useful for compression, since it tends to be easy to compress a string that has runs of repeated  characters.
[For more info](https://en.wikipedia.org/wiki/Burrows%E2%80%93Wheeler_transform)

---
</details>

<details>
<summary>Huffman Compressor</summary>
</details>
<details>
<summary>Shannon-Fano Compressor</summary>
</details>

---
</details>

**Comment by siriak** [comment]
Nice idea, could you help with the migration?

**Comment by GeorgeS2019** [comment]
@siriak Only if [community centered issue](https://github.com/TheAlgorithms/C-Sharp/issues/277) is addressed. Sincere feedback here, it is not uncommon that the license can change. Community centered project OFTEN SPENDS a great deal of time **assuring** that it will stay MIT for the whole duration of time to assure continuous user commitment.

**Comment by siriak** [comment]
This issue is not related to licensing in any way, is it?
