### ISSUE TITLE
The implementation of InsertionSorter is wrong

### ISSUE THREAD

**Issue by ramiroezequielalvarez** [TheAlgorithms/C-Sharp#304]
The implementation of InsertionSorter  is wrong.  It's a copy of selection sort

Wikipedia example (InsersionSort)

i ← 1
while i < length(A)
    j ← i
    while j > 0 and A[j-1] > A[j]
        swap A[j] and A[j-1]
        j ← j - 1
    end while
    i ← i + 1
end while

currently InsertionSorter is equal to SelectionSorter

**Comment by siriak** [comment]
Please open a PR, it's hard to read code when it's not formatted
