### ISSUE TITLE
16th of December 2022: LGTM.com will be shut down

### ISSUE THREAD

**Issue by pea-sys** [TheAlgorithms/C-Sharp#329]
LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by siriak** [comment]
We've disabled LGTM, thanks for reporting this issue!
