### ISSUE TITLE
[FEATURE] Add Algorithm for counting set bits in an integer

### ISSUE THREAD

**Issue by Rytnix** [TheAlgorithms/C-Sharp#359]
I propose to add [algorithm] [set bit count in a number]. It helps to solve problems such as [calculating the no of set bits ]. It's best described on the website(s): [https://www.geeksforgeeks.org/count-set-bits-in-an-integer/].

**Comment by siriak** [comment]
What is the algorithm you would like to add? If it i-th bit in a number, would'nt that be just something like `n |= (1 << i)`?

**Comment by Rytnix** [comment]
No no, This algorithm will count the no of 1's i.e set bits that is present in a number, Ex if the number is 5(101 in bits) then the set bit count will be 2.
