### ISSUE TITLE
Improve Stack array based algorithms

### ISSUE THREAD

**Issue by JoaoVictor6** [TheAlgorithms/C-Sharp#372]
I propose to refactor Stack ArrayBasedStack. I was reading some C# algorithms and not understand the reason for use a iteration in line 48 of [ArrayBasedStack.cs](https://github.com/TheAlgorithms/C-Sharp/blob/master/DataStructures/Stack/ArrayBasedStack.cs#L48) . I believe this syntax is more readable:
```csharp
public ArrayBasedStack(T[] items)
{
    stack = items;
    top = items.Length - 1;
}
```

If this refactoring makes sense, I can make this change :)

**Comment by siriak** [comment]
The proposed change seems correct, could you make a PR with it and a test to check that it works?

**Comment by siriak** [comment]
Done
