### ISSUE TITLE
SieveOfEratosthenes.cs isn't the Sieve of Eratosthenes

### ISSUE THREAD

**Issue by deljohnson1** [TheAlgorithms/C-Sharp#374]
This is a great project and I would like to help.

I think you should have a prime class and a variety of ways to calculate primes. What is in the SieveOfEratosthenes.cs file is calculating primes by dividing the number by all primes using memoization of previously calculated primes.

https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

**Comment by siriak** [comment]
I agree, the current implementation is incorrect. Could you make a PR to fix that?

**Comment by deljohnson1** [comment]
Please provide me feedback for the PRs. I am new to github, so hopefully I did it correctly.

**Comment by siriak** [comment]
You haven't made a PR in this repository yet
