### ISSUE TITLE
Recommend adding a CountOfDivisors function to Algorithms.Numeric

### ISSUE THREAD

**Issue by deljohnson1** [TheAlgorithms/C-Sharp#382]
Recommend adding a BigInteger CountOfDivisors(BigInteger n) function to Algorithms.Numeric.

Also recommend modifying DivisorsCountSequence.cs to use that function. Current algorithm of DivisorsCountSequence.cs is O(n) for each n, when it should be O(sqrt(n)).

**Comment by siriak** [comment]
@deljohnson1 feel free to create a PR with the proposed fixes
