### ISSUE TITLE
C# implementation of binary search does not run.

### ISSUE THREAD

**Issue by Rademenes16** [TheAlgorithms/C-Sharp#400]
**Describe the bug**
Binary seach algorithm in C# does not run.

**To Reproduce**
Run provided C# code.

Error:

```
---- RESET ----
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-bin/Debug/net5.0/533c8da4-37af-497a-ad63-1458bee97c5d.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Exited with code 1

```
https://the-algorithms.com/algorithm/binary-search?lang=c-sharp

**Comment by 7IronSnow7** [comment]
Hey so I copied the code and tested it out on visual studio. 

I found that you were missing a main entry point. "Program does not contain a static 'Main' method suitable for an entry point".

So try this out:

**Comment by 7IronSnow7** [comment]
Hey, so I copied the code and tested it out on Visual Studio.

I found that you were missing a main entry point. "Program does not contain a static 'Main' method suitable for an entry point".

So try this out: (Input this after  "public class BinarySearcher<T> where T : IComparable<T>{" )

class Program
    {
        static void Main(string[] args)
        {
            // Your code to test the BinarySearcher can be placed here
            // For example:
            int[] sortedArray = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
            int searchValue = 7;
            BinarySearcher<int> searcher = new BinarySearcher<int>();
            int result = searcher.FindIndex(sortedArray, searchValue);
            Console.WriteLine($"Index of {searchValue} is: {result}");
        }
    }

I hope this helps, feel free to message me if you do not understand anything.

**Comment by siriak** [comment]
@Rademenes16 these are not supposed to be executed as-is. You can add an entry point if you want to test it online or create an app that uses this project as a library

**Comment by Upendra-Allagadda** [comment]
Please close this if this is an invalid open issue.
