### ISSUE TITLE
Implement a common BlockCipherPadding Interface

### ISSUE THREAD

**Issue by Kalkwst** [TheAlgorithms/C-Sharp#410]
We currently have four algorithms that implement block cipher padding. These implementations essentially share the same functions: `AddPadding`, `RemovePadding` and `GetPaddingCount`.

I am also planning to add three more padding algorithms that are essentially block cipher paddings.

Having a common interface would help maintain uniformity among all these algorithms.

Looking forward to your thoughts on this.

**Comment by siriak** [comment]
Done
