### ISSUE TITLE
Replace System.Drawing.Common

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#441]
We need to replace System.Drawing.Common with something else because it's Windows-only since version 6.

I propose to use [SkiaSharp](https://github.com/mono/SkiaSharp) instead. It's one of the alternatives to System.Drawing.Common Microsoft recommends [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). Compared to other alternatives, it looks more popular and better maintained.

I'm not familiar with the interface SkiaSharp provides, but I assume it's different from what System.Drawing.Common has. Nevertheless, we use only the most basic drawing features in the repository, so it should be not too difficult to migrate.

This update is a part of #425.

**Comment by siriak** [comment]
@gmottajr will you be able to do the upgrade?

**Comment by gmottajr** [comment]
Sounds good, @siriak!
Let's work on it.

**Comment by siriak** [comment]
Here is TheAlgorithms server https://discord.gg/c7MnfGFGa6

**Comment by siriak** [comment]
@gmottajr, how are you doing? Do you still plan to implement this or it can be grabbed by somebody else?

**Comment by siriak** [comment]
This is completed
