### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#442]
As a part of migration to .NET 8 in #425, we need to update to the latest major versions of the libraries we use:
- [x] coverlet.collector to 6.*
- [x] FluentAssertions to 6.*
- [x] Microsoft.NET.Test.Sdk to 17.*
- [ ] NUnit to 4.*

Feel free to grab and update one of them!

**Comment by SureshRepos** [comment]
Hi Andrii,
I would like to pick this one up, could you please assign it to me?
Also can I update all four packages in a single PR or do you have a preference? 
Can work on it ASAP once you confirm.
Thank You!
