### ISSUE TITLE
Invasor de rede 

### ISSUE THREAD

**Issue by Esk-C** [TheAlgorithms/C-Sharp#456]
using System;
using System.Net;
using System.Net.Sockets;

class Program
{
    static void Main()
    {
        string ipAddress = "192.168.1.1"; // Endereço IP da rede que você deseja escanear
        int startPort = 1;
        int endPort = 1024;

        Console.WriteLine($"Scanning {ipAddress} from port {startPort} to {endPort}");

        for (int port = startPort; port <= endPort; port++)
        {
            using (TcpClient tcpClient = new TcpClient())
            {
                try
                {
                    tcpClient.Connect(ipAddress, port);
                    Console.WriteLine($"Port {port} is open.");
                }
                catch (Exception)
                {
                    // Porta fechada ou inacessível
                }
            }
        }

        Console.WriteLine("Scan complete.");
    }
}

**Comment by siriak** [comment]
Please open a pull request in English with a good explanation and references for the algorithm

**Comment by Esk-C** [comment]
What did I do?

Em qui., 18 de jul. de 2024 17:19, Andrii Siriak ***@***.***>
escreveu:

**Comment by Esk-C** [comment]
Did you want to talk to me?

Em qui., 18 de jul. de 2024 17:19, Andrii Siriak ***@***.***>
escreveu:
