### ISSUE TITLE
Abertura de fechaduras eletrônicas 

### ISSUE THREAD

**Issue by Esk-C** [TheAlgorithms/C-Sharp#457]
using System;
using InTheHand.Net.Sockets;
using InTheHand.Net.Bluetooth;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        string deviceAddress = "00:11:22:33:44:55"; // Endereço MAC do dispositivo Bluetooth
        Guid serviceUuid = new Guid("00001101-0000-1000-8000-00805F9B34FB"); // UUID do serviço Bluetooth

        try
        {
            BluetoothAddress address = BluetoothAddress.Parse(deviceAddress);
            BluetoothClient client = new BluetoothClient();
            client.Connect(new BluetoothEndPoint(address, serviceUuid));

            using (NetworkStream stream = client.GetStream())
            using (StreamWriter writer = new StreamWriter(stream))
            using (StreamReader reader = new StreamReader(stream))
            {
                // Enviar comando para abrir a fechadura
                writer.WriteLine("OPEN"); // O comando específico depende do dispositivo
                writer.Flush();

                // Ler resposta do dispositivo
                string response = reader.ReadLine();
                Console.WriteLine("Response: " + response);
            }

            client.Close();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}

**Comment by siriak** [comment]
Please open a pull request in English with a good explanation and references for the algorithm

**Comment by Esk-C** [comment]
Oq eu fiz ?

Em qui., 18 de jul. de 2024 17:19, Andrii Siriak ***@***.***>
escreveu:

**Comment by Esk-C** [comment]
What did I do?

Em qui., 18 de jul. de 2024 17:23, Esk ***@***.***> escreveu:

**Comment by siriak** [comment]
You have opened an issue

**Comment by Esk-C** [comment]
Did I do something wrong?

Em sex., 19 de jul. de 2024 03:20, Andrii Siriak ***@***.***>
escreveu:
