### ISSUE TITLE
RoaringBitmap

### ISSUE THREAD

**Issue by sgf** [TheAlgorithms/C-Sharp#461]
I propose to add data structure RoaringBitmap .It's best described in book(s), on website(s): https://github.com/RoaringBitmap/RoaringBitmap.

 It helps to solve problems such as :

> Bitsets, also called bitmaps, are commonly used as fast data structures. Unfortunately, they can use too much memory. To compensate, we often use compressed bitmaps.
> 
> Roaring bitmaps are compressed bitmaps which tend to outperform conventional compressed bitmaps such as WAH, EWAH or Concise. In some instances, roaring bitmaps can be hundreds of times faster and they often offer significantly better compression. They can even be faster than uncompressed bitmaps.

.net has always lacked relevant high-quality implementations/ports. Of course, this is just a suggestion. 
Do you consider porting or if you can have a better alternative structure, it would be even better.

**Comment by siriak** [comment]
The data structure looks very interesting, I think it would be great to add it to our collection. If you want to add it, feel free to open a PR with it and tests. Alternatively, I could mark this issue as `help wanted`, and wait for somebody interested to implement it.

**Comment by sgf** [comment]
I really want to implement this data structure, but if I had enough time, I would have started it a long time ago.
The fact is, I clearly don't have enough time. Of course, if I made a living doing open source projects, I might have enough time to do it.
But for now, I still need to spend most of my time on my full-time job. Even if it's only $3,000 a month, at least it's guaranteed.
