### ISSUE TITLE
Conflicting .NET versions on the docs

### ISSUE THREAD

**Issue by RicardoRibeiroRodrigues** [TheAlgorithms/C-Sharp#463]
**Describe the Bug:**
There is an inconsistency in the project documentation. The `README.md` file states that the project uses the .NET 8 SDK, but the `CONTRIBUTING.md` file mentions that it uses the .NET 6 SDK. It seems like the `CONTRIBUTING.md` file might be outdated. If this is the case, I'd be happy to submit a PR to fix it.

**Comment by siriak** [comment]
Yes, you are correct. Please submit a PR and I'll gladly review it. Thanks!
