### ISSUE TITLE
Repository file structure and code style is not conventional

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#47]
This repo contains a bunch of good algorithms and data structures. Unfortunately, in my opinion, they are not organized well (I mean naming conventions and folder structure). Naming and structure don't conform to the best practices that are used in C# projects.  I would like to volunteer and get this work done in my free time if owners don't mind. I hope that will give this repo a fresh look.

**Comment by harshildarji** [comment]
@siriak Hey, Sorry for the delay! 
If you want to contribute to this repo, You're welcome to do so. 
Thank you.
