### ISSUE TITLE
Dev container

### ISSUE THREAD

**Issue by Paulofalcao2002** [TheAlgorithms/C-Sharp#481]
Hi guys! 

I was looking to setup this project on my local machine and thought it would really help to have a devcontainer like in some open source projects, like [TheAlgorithms/Python](https://github.com/TheAlgorithms/Python)

Does it make sense?

I am studying this use of containers, so I could implement it.

**Comment by siriak** [comment]
I haven't worked with devcontainers before, but if you implement it, I will gladly review it
