### ISSUE TITLE
Refresh algorithms

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/C-Sharp#52]
I propose to update all algorithms to match coding standards. As a reference, please take a look at already refreshed algorithms. I will update this checklist as necessary. Feel free to make PRs and reference this issue there.

**Encoders**
- [x] Caesar
- [x] Hill
- [x] Vigenere

**Data Compression**
- [x] Huffman Encoding
- [x] Shannon-Fano Encoding

**Numeric**
- [x] Binary GCD
- [x] Euclidean GCD
- [x] Other
- [x] Fermat Prime Checker
- [x] Prime Finder
- [x] Sieve of Eratosthenes
- [x] Vowel Checker
- [x] Searches
- [x] A-Star
- [x] Binary
- [x] Linear

**Sorts**
- [x] Binary Insertion
- [x] Bogo
- [x] Bubble
- [x] Bucket
- [x] Cocktail
- [x] Cycle
- [x] Heap
- [x] Insertion
- [x] Merge
- [x] Pancake
- [x] Quick
- [x] Radix
- [x] Selection
- [x] Shell

**String**
- [x] Longest Consecutive Character
- [x] Palindrome Checker

**Traversals**
- [x] Tree Traversal

**Comment by justindongqiang** [comment]
I can work it. Where is the coding standards reference?

**Comment by siriak** [comment]
@justindongqiang , take a look at BubbleSorter, CaesarEncoder or VigenereEncoder, these classes are well-written. In general, the process is as follows:

1. Add an interface that a bunch of classes will implement (interface ISorter) (if it's not added yet)
2. Add a class that implements the interface (class BubbleSorter)
3. Write an algorithm in corresponding method (method Sort)
4. Add unit tests to check whether the algorithm works correctly (class BubbleSorterTests)

Step 4 can be implemented later. Also please write which algorithm(s) you will be working on, so that others won't work on them.

**Comment by siriak** [comment]
Cool, we did it! Thanks to everyone who helped to make it happen, especially to the most frequent contributor @1fisedi
